-- ==========================================
-- ACCEPT REC REDESIGN - BLOG SCHEMA
-- ==========================================

-- 1. Táblák létrehozása
CREATE TABLE IF NOT EXISTS public.blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blog_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    category_slug TEXT REFERENCES public.blog_categories(slug) ON DELETE SET NULL,
    author TEXT,
    published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Blog címkék kapcsolótábla (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.blog_post_tags (
    blog_id BIGINT REFERENCES public.blogs(id) ON DELETE CASCADE,
    tag_slug TEXT REFERENCES public.blog_tags(slug) ON DELETE CASCADE,
    PRIMARY KEY (blog_id, tag_slug)
);

-- 2. Row Level Security (RLS) beállítása
-- Jelenleg kikapcsolva (vagy mindenki számára olvasható), hogy egyszerű legyen az átállás.
-- Később az admin műveleteket auth-hoz kell kötni.

ALTER TABLE public.blog_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_post_tags ENABLE ROW LEVEL SECURITY;

-- Mindenki olvashatja
CREATE POLICY "Public profiles are viewable by everyone." ON public.blog_categories FOR SELECT USING (true);
CREATE POLICY "Public profiles are viewable by everyone." ON public.blog_tags FOR SELECT USING (true);
CREATE POLICY "Public profiles are viewable by everyone." ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Public profiles are viewable by everyone." ON public.blog_post_tags FOR SELECT USING (true);

-- Fejlesztés idejére mindenkinek engedélyezzük a módosítást is (VIGYÁZAT: élesben ezt cserélni kell auth-hoz!)
CREATE POLICY "Allow all insert." ON public.blog_categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update." ON public.blog_categories FOR UPDATE USING (true);
CREATE POLICY "Allow all delete." ON public.blog_categories FOR DELETE USING (true);

CREATE POLICY "Allow all insert." ON public.blog_tags FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update." ON public.blog_tags FOR UPDATE USING (true);
CREATE POLICY "Allow all delete." ON public.blog_tags FOR DELETE USING (true);

CREATE POLICY "Allow all insert." ON public.blogs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update." ON public.blogs FOR UPDATE USING (true);
CREATE POLICY "Allow all delete." ON public.blogs FOR DELETE USING (true);

CREATE POLICY "Allow all insert." ON public.blog_post_tags FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all delete." ON public.blog_post_tags FOR DELETE USING (true);


-- 3. Minta adatok feltöltése (Seed)
INSERT INTO public.blog_categories (name, slug) VALUES 
('Workforce Strategy', 'workforce-strategy'),
('Client Success', 'client-success'),
('Industry Insight', 'industry-insight'),
('Company News', 'company-news'),
('Technology', 'technology')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.blog_tags (name, slug) VALUES 
('technology', 'technology'),
('attendance', 'attendance'),
('workforce', 'workforce'),
('case-study', 'case-study'),
('logistics', 'logistics'),
('rapid-deployment', 'rapid-deployment'),
('fill-rates', 'fill-rates'),
('performance', 'performance'),
('recruitment', 'recruitment')
ON CONFLICT (slug) DO NOTHING;
