-- ==========================================
-- ACCEPT REC REDESIGN - TEAM MEMBERS SCHEMA
-- ==========================================

-- 1. Tábla létrehozása
CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    location TEXT DEFAULT 'Leicester',
    quote TEXT,
    superpower TEXT,
    motto TEXT,
    loves TEXT[] DEFAULT '{}',
    image_url TEXT,
    disney_image_url TEXT,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. RLS beállítása
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all select on team_members" ON public.team_members FOR SELECT USING (true);
CREATE POLICY "Allow all insert on team_members" ON public.team_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update on team_members" ON public.team_members FOR UPDATE USING (true);
CREATE POLICY "Allow all delete on team_members" ON public.team_members FOR DELETE USING (true);

-- 3. Storage Bucket létrehozása
-- Megjegyzés: A storage.buckets táblába való beszúrás csak akkor működik, ha van megfelelő jogosultság.
-- Ha hibát dob, az admin felületen manuálisan is létrehozható a 'team' bucket.
INSERT INTO storage.buckets (id, name, public)
VALUES ('team', 'team', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policy-k (hogy lehessen feltölteni/olvasni)
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'team');
CREATE POLICY "Admin Insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'team');
CREATE POLICY "Admin Update" ON storage.objects FOR UPDATE USING (bucket_id = 'team');
CREATE POLICY "Admin Delete" ON storage.objects FOR DELETE USING (bucket_id = 'team');

-- 4. Kezdő adatok (Seed) a jelenlegi OurTeamPageClient.js-ből
INSERT INTO public.team_members (name, role, location, quote, superpower, motto, loves, image_url, disney_image_url, order_index)
VALUES 
('Mark Pearce', 'Managing Director', 'Leicester', 'Big sports fan - you''ll find me on the golf course or cricket pitch when I''m not filling shifts!', 'Turning chaos into order (and dad jokes into groans)', 'Every storm eventually gives way to a beautiful rainbow', ARRAY['Golf', 'Cricket', 'Building Empires'], '/Mark-front.webp', '/mark-funny.webp', 0),
('Monika Loj', 'Operations Director', 'Leicester', 'I keep the whole operation running smoothly - think of me as the engine room!', 'Making 100 temps appear out of thin air', 'Excellence in execution', ARRAY['Organization', 'Coffee', 'Efficiency'], '/Monika-Beldycka-f.webp', '/Monika-Beldycka-f.webp', 1),
('Kevin Highet', 'Commercial Director', 'Leicester', 'I''m the numbers guy who makes sure we''re not just busy, but profitable!', 'Turning opportunities into partnerships', 'Commercial success comes from smart decisions', ARRAY['Strategy', 'Growth', 'Good Data'], '/kevin-highet.webp', '/team-1.webp', 2),
('Elly Clow', 'Head of Sales', 'Leicester', 'I lead our sales team and make sure we''re winning the right clients - not just any clients!', 'Building relationships that last', 'Sales is about helping, not selling', ARRAY['New Business', 'Networking', 'Winning'], '/elly-clow.webp', '/elly-clow.webp', 3),
('Agnieszka Jasinska', 'Head of Operations', 'Leicester', 'I manage the big accounts and make sure everything runs like clockwork!', 'Keeping complex operations simple', 'Consistency is key', ARRAY['Problem Solving', 'Big Logistics', 'Sunsets'], '/Aggie-Jasinska-f.webp', '/Aggie-Jasinska-f.webp', 4),
('Natalia Wielgosz', 'Head of Accounts & Payroll', 'Leicester', 'I make sure everyone gets paid on time, every time. It''s what I do!', 'Friday payroll runs smoother than butter', 'Accuracy matters', ARRAY['Spreadsheets', 'Smooth Fridays', 'Accuracy'], '/Talki_New.webp', '/Talki_New.webp', 5),
('Peter Czinderi', 'IT Manager', 'Leicester', 'I keep all our systems running and make sure technology works FOR us, not against us!', 'Making tech simple', 'If it''s not automated, it should be', ARRAY['Automation', 'Latest Gadgets', 'Zero Downtime'], '/Peter-turkus.webp', '/Peter-turkus.webp', 6),
('Monika Cyrson', 'Resourcing Manager', 'Leicester', 'I find the right people for the right roles. It''s like matchmaking, but for work!', 'Knowing exactly who to call', 'The right person in the right place', ARRAY['Interviews', 'Finding Talent', 'Career Stories'], '/Monika_Cyrson_f.jpg', '/Monika_Cyrson_f.jpg', 7),
('Magdalena Walker', 'Branch Manager', 'Leicester', 'I run our branch like a well-oiled machine. Everyone knows where they stand!', 'Keeping everyone on track', 'Lead by example', ARRAY['Leadership', 'Teamwork', 'Morning Huddles'], '/Magda-Obraczka.webp', '/Magda-Obraczka.webp', 8),
('Radoslaw Plewa', 'Managed Services Manager', 'Leicester', 'I manage our biggest client accounts and make sure they get exactly what they need!', 'Calm under pressure', 'Consistency wins clients', ARRAY['Big Projects', 'Client Satisfaction', 'Resilience'], '/Radoslaw-Plewa.webp', '/Radoslaw-Plewa.webp', 9),
('Jamie Ellis', 'Marketing Team Leader', 'Leicester', 'Started as a Digital Marketing Apprentice in 2020 and now lead all our marketing efforts!', 'Crafting social content that actually engages people', 'Excellence through creativity', ARRAY['Branding', 'Creative Ads', 'Analytics'], '/Jamie-Ellis.webp', '/Jamie-Ellis.webp', 10),
('Maja Wojtaszko', 'Senior Driving Account Manager', 'Bristol', 'I specialize in driver recruitment - from HGV to delivery, I know the roads!', 'Finding drivers who actually show up', 'Keep on trucking', ARRAY['Driving Logistics', 'Road Trips', 'Happy Drivers'], '/maja.webp', '/maja.webp', 11),
('Joanna Antecka', 'Branch Manager', 'Leicester', 'I keep our branch running smoothly and make sure every client and candidate feels valued!', 'Making everyone feel heard', 'People make the difference', ARRAY['Interviews', 'Community', 'Branch Growth'], '/Joanna-Antecka.webp', '/Joanna-Antecka.webp', 12);
